---

- hosts: all
  tasks:
  - name: install apache & php package
    dnf:
      name:
        - httpd.aarch64
        - php.aarch64
      state: latest
      update_cache: true
    when: ansible_distribution == "RedHat"
