---

- hosts: all
  tasks:
  - name: update repository index
    dnf:
      update_cache: true

  - name: install httpd package
    dnf:
      name: httpd.aarch64
      state: latest

  - name: install php package
    dnf:
      name: php.aarch64
      state: latest
